/// firebase_config.dart
/// ---------------------
/// Firebase initialization & shared Firestore/Auth instances.
///
/// HOW TO USE
/// 1. Run `flutterfire configure` (see docs/SETUP.md).
/// 2. Import this file wherever you need `firestore` or `auth`.
///
/// Folder: lib/services/firebase/

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by flutterfire configure

/// Call once in main() before runApp().
Future<void> initFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Enable Firestore offline persistence (useful for mobile).
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );
}

/// Convenience getters used across the service layer.
FirebaseFirestore get firestore => FirebaseFirestore.instance;
FirebaseAuth get auth => FirebaseAuth.instance;

/// The currently signed-in user's UID (null when not authenticated).
String? get currentUid => auth.currentUser?.uid;
