// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMBHMZOT5LNPga1jMHfllm6_YQf3VtSrg',
    appId: '1:165060165976:web:64673ea9434a50b668a52d',
    messagingSenderId: '165060165976',
    projectId: 'goaldigger-2026',
    authDomain: 'goaldigger-2026.firebaseapp.com',
    storageBucket: 'goaldigger-2026.firebasestorage.app',
    measurementId: 'G-9E9NXKXJ6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpX_qWgK_i5TyAiDZjw1Lq7kTDkOqy4WQ',
    appId: '1:165060165976:android:5534e600954d297768a52d',
    messagingSenderId: '165060165976',
    projectId: 'goaldigger-2026',
    storageBucket: 'goaldigger-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPzrNwTCHFOlUsxK-vil4aaLLiVdQz8t0',
    appId: '1:165060165976:ios:cb771a97b427d35768a52d',
    messagingSenderId: '165060165976',
    projectId: 'goaldigger-2026',
    storageBucket: 'goaldigger-2026.firebasestorage.app',
    iosClientId: '165060165976-72m7r0rsa3prhfoguv1bs6qoee9n7d16.apps.googleusercontent.com',
    iosBundleId: 'com.example.fltrTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPzrNwTCHFOlUsxK-vil4aaLLiVdQz8t0',
    appId: '1:165060165976:ios:cb771a97b427d35768a52d',
    messagingSenderId: '165060165976',
    projectId: 'goaldigger-2026',
    storageBucket: 'goaldigger-2026.firebasestorage.app',
    iosClientId: '165060165976-72m7r0rsa3prhfoguv1bs6qoee9n7d16.apps.googleusercontent.com',
    iosBundleId: 'com.example.fltrTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMBHMZOT5LNPga1jMHfllm6_YQf3VtSrg',
    appId: '1:165060165976:web:c7985d6b3b965bee68a52d',
    messagingSenderId: '165060165976',
    projectId: 'goaldigger-2026',
    authDomain: 'goaldigger-2026.firebaseapp.com',
    storageBucket: 'goaldigger-2026.firebasestorage.app',
    measurementId: 'G-J6ZNV7MPY6',
  );
}
