import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../state/app_state.dart';
import '../models/sub_task.dart';
import '../models/goal_item.dart';
import '../theme/colors.dart';
import '../theme/text_styles.dart';
import '../widgets/glass_card.dart';

class CalendarScreen extends StatelessWidget {
  const CalendarScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final state = context.watch<AppState>();
    const dayNames = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    const startOffset = 2;
    const daysInMonth = 30;
    const prevDays = 31;

    // Build per-day map
    final tasksByDay = <int, List<SubTask>>{};
    for (final g in state.goals) {
      for (final s in g.subtasks) {
        (tasksByDay[s.scheduledDay] ??= []).add(s);
      }
    }

    final cells = List.generate(42, (i) {
      final day = i - startOffset + 1;
      final isPrev = day < 1;
      final isNext = day > daysInMonth;
      return _Cell(
        day: day,
        displayDay: isPrev ? prevDays + day : isNext ? day - daysInMonth : day,
        isOutside: isPrev || isNext,
      );
    });

    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 120),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('FULL CALENDAR VIEW · BUILT BY ATS', style: AppTextStyles.labelTeal),
                    const SizedBox(height: 16),
                    Text('Calendar', style: AppTextStyles.heading1),
                    const SizedBox(height: 12),
                    Text('All sub-tasks generated by Adaptive Task Suggestions are scheduled across the month.',
                        style: AppTextStyles.body),
                  ],
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: BoxDecoration(color: Colors.white.withValues(alpha: 0.75), borderRadius: BorderRadius.circular(100)),
                child: const Text('April 2026',
                    style: TextStyle(fontSize: 13, fontWeight: FontWeight.w900, color: AppColors.textSecondary)),
              ),
            ],
          ),
          const SizedBox(height: 20),

          // Goal legend
          Wrap(
            spacing: 6, runSpacing: 6,
            children: state.goals.map((g) => Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              decoration: BoxDecoration(
                gradient: LinearGradient(colors: [g.startColor, g.endColor]),
                borderRadius: BorderRadius.circular(100),
              ),
              child: Text('★${g.importance} · ${g.title} · ⏰ Apr ${g.deadlineDay}',
                  style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: Colors.white)),
            )).toList(),
          ),

          const SizedBox(height: 20),

          // Calendar grid
          GlassCard(
            padding: const EdgeInsets.all(12),
            child: Column(
              children: [
                Row(
                  children: dayNames.map((n) => Expanded(
                    child: Center(child: Text(n.toUpperCase(), style: AppTextStyles.label.copyWith(fontSize: 9, letterSpacing: 1.4))),
                  )).toList(),
                ),
                const SizedBox(height: 8),
                ...List.generate(6, (week) {
                  final weekCells = cells.skip(week * 7).take(7).toList();
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 5),
                    child: Row(
                      children: weekCells.map((c) {
                        final sel = c.day == state.selectedDay && !c.isOutside;
                        final isToday = c.day == AppState.todayDay && !c.isOutside;
                        final dayItems = !c.isOutside ? (tasksByDay[c.day] ?? []) : <SubTask>[];
                        final dayDeadlines = !c.isOutside ? state.goals.where((g) => g.deadlineDay == c.day).toList() : <GoalItem>[];

                        return Expanded(
                          child: GestureDetector(
                            onTap: c.isOutside ? null : () => state.setSelectedDay(c.day),
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 300),
                              margin: const EdgeInsets.symmetric(horizontal: 2),
                              padding: const EdgeInsets.all(4),
                              constraints: const BoxConstraints(minHeight: 90),
                              decoration: BoxDecoration(
                                color: sel
                                    ? AppColors.dark
                                    : c.isOutside
                                        ? Colors.white.withValues(alpha: 0.2)
                                        : isToday
                                            ? const Color(0xFFFEF3C7)
                                            : Colors.white.withValues(alpha: 0.6),
                                borderRadius: BorderRadius.circular(14),
                                border: isToday && !sel ? Border.all(color: AppColors.amberWarm, width: 2) : null,
                                boxShadow: sel ? [BoxShadow(color: AppColors.dark.withValues(alpha: 0.22), blurRadius: 35, offset: const Offset(0, 14))] : [],
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                    children: [
                                      Text('${c.displayDay}',
                                          style: TextStyle(
                                              fontSize: 12, fontWeight: FontWeight.w900,
                                              color: sel
                                                  ? Colors.white
                                                  : c.isOutside
                                                      ? AppColors.textTertiary.withValues(alpha: 0.4)
                                                      : AppColors.textSecondary)),
                                      if (isToday && !sel)
                                        const Text('•', style: TextStyle(color: AppColors.amberWarm, fontSize: 14, fontWeight: FontWeight.w900)),
                                    ],
                                  ),
                                  if (dayDeadlines.isNotEmpty) ...[
                                    const SizedBox(height: 2),
                                    Wrap(
                                      spacing: 2,
                                      children: dayDeadlines.map((g) => Container(
                                        width: 6, height: 6,
                                        decoration: BoxDecoration(
                                          shape: BoxShape.circle,
                                          gradient: LinearGradient(colors: [g.startColor, g.endColor]),
                                        ),
                                      )).toList(),
                                    ),
                                  ],
                                  const SizedBox(height: 3),
                                  ...dayItems.take(2).map((s) {
                                    final goal = state.goals.firstWhere((g) => g.id == s.goalId);
                                    return Container(
                                      margin: const EdgeInsets.only(top: 1),
                                      padding: const EdgeInsets.symmetric(horizontal: 3, vertical: 1),
                                      decoration: BoxDecoration(
                                        gradient: sel ? null : LinearGradient(colors: [goal.startColor.withValues(alpha: 0.9), goal.endColor.withValues(alpha: 0.9)]),
                                        color: sel ? Colors.white.withValues(alpha: 0.15) : null,
                                        borderRadius: BorderRadius.circular(4),
                                      ),
                                      child: Text(
                                        '${s.done ? "✓ " : ""}${s.title}',
                                        maxLines: 1, overflow: TextOverflow.ellipsis,
                                        style: const TextStyle(fontSize: 7, fontWeight: FontWeight.w900, color: Colors.white),
                                      ),
                                    );
                                  }),
                                  if (dayItems.length > 2)
                                    Padding(
                                      padding: const EdgeInsets.only(top: 1),
                                      child: Text('+${dayItems.length - 2} more',
                                          style: TextStyle(
                                              fontSize: 7, fontWeight: FontWeight.w900,
                                              color: sel ? Colors.white60 : AppColors.textTertiary)),
                                    ),
                                ],
                              ),
                            ),
                          ),
                        );
                      }).toList(),
                    ),
                  );
                }),
              ],
            ),
          ),

          const SizedBox(height: 20),

          // Selected day details (replaces old "selected day" — now shows scheduled subtasks of that day, not blocks)
          GlassCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('APRIL ${state.selectedDay}${state.selectedDay == AppState.todayDay ? " · TODAY" : ""}',
                    style: AppTextStyles.label),
                const SizedBox(height: 6),
                const Text('Scheduled sub-tasks',
                    style: TextStyle(fontSize: 22, fontWeight: FontWeight.w900, letterSpacing: -1, color: AppColors.textPrimary)),
                if (state.goals.any((g) => g.deadlineDay == state.selectedDay)) ...[
                  const SizedBox(height: 10),
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(color: const Color(0xFFFEF3C7), borderRadius: BorderRadius.circular(16)),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('⏰ DEADLINE TODAY', style: AppTextStyles.label.copyWith(color: const Color(0xFFB45309), fontSize: 9)),
                        const SizedBox(height: 4),
                        Text(state.goals.where((g) => g.deadlineDay == state.selectedDay).map((g) => g.title).join(' · '),
                            style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w900, color: Color(0xFF78350F))),
                      ],
                    ),
                  ),
                ],
                const SizedBox(height: 14),
                ...((tasksByDay[state.selectedDay] ?? <SubTask>[]).map((t) {
                  final goal = state.goals.firstWhere((g) => g.id == t.goalId);
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 8),
                    child: GestureDetector(
                      onTap: () => state.toggleTask(t.id),
                      child: Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: t.done ? AppColors.emerald.withValues(alpha: 0.1) : Colors.white.withValues(alpha: 0.8),
                          borderRadius: BorderRadius.circular(16),
                        ),
                        child: Row(
                          children: [
                            Container(
                              width: 36, height: 36,
                              decoration: BoxDecoration(
                                shape: BoxShape.circle,
                                color: t.done ? AppColors.emerald : AppColors.dark.withValues(alpha: 0.05),
                                border: Border.all(color: t.done ? AppColors.emerald : AppColors.dark.withValues(alpha: 0.1)),
                              ),
                              child: Center(
                                child: t.done
                                    ? const Icon(Icons.check_rounded, color: Colors.white, size: 16)
                                    : Text('${goal.importance}',
                                        style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: AppColors.textSecondary)),
                              ),
                            ),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(t.title, style: TextStyle(
                                    fontSize: 13, fontWeight: FontWeight.w900,
                                    color: t.done ? AppColors.textTertiary : AppColors.textPrimary,
                                    decoration: t.done ? TextDecoration.lineThrough : null,
                                  )),
                                  const SizedBox(height: 2),
                                  Text('${t.duration} · ${goal.title}',
                                      style: AppTextStyles.bodySmall.copyWith(fontSize: 11)),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                })),
                if ((tasksByDay[state.selectedDay] ?? <SubTask>[]).isEmpty)
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(color: AppColors.dark.withValues(alpha: 0.05), borderRadius: BorderRadius.circular(16)),
                    child: const Center(child: Text("Open day — ATS may pull from this if you finish today's work.",
                        style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: AppColors.textTertiary))),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Cell {
  final int day, displayDay;
  final bool isOutside;
  _Cell({required this.day, required this.displayDay, required this.isOutside});
}
