import 'package:flutter/material.dart';

const Color gdBackground = Color(0xFFF7F8FC);
const Color gdSurface = Color(0xFFFFFFFF);
const Color gdInk = Color(0xFF263247);
const Color gdMuted = Color(0xFF5F6B7A); // readable but softer secondary text
const Color gdPrimary = Color(0xFF315C9D);
const Color gdPrimaryDark = Color(0xFF496DA8);
const Color gdPrimarySoft = Color(0xFFE8F0FE);
const Color gdAccent = Color(0xFFE66A6A);
const Color gdAccentSoft = Color(0xFFFFE4E6);
const Color gdWarning = Color(0xFFC2410C);
const Color gdError = Color(0xFFDC2626);
const Color gdErrorSoft = Color(0xFFFEE2E2);
const Color gdBorder = Color(0xFFE2E8F0); // soft modern border color
const Color gdBorderStrong = Color(0xFFCBD5E1); // stronger border color
const Color gdHint = Color(0xFF64748B); // hint text color
const Color gdGradientCareerFrom = Color(0xFF06B6D4); // career gradient start
const Color gdGradientCareerTo = Color(0xFF2563EB); // career gradient end
const Color gdGradientStudyFrom = Color(0xFFF59E0B); // study gradient start
const Color gdGradientStudyTo = Color(0xFFEC4899); // study gradient end
const Color gdGradientWellnessFrom = Color(0xFFFB7185); // wellness gradient start
const Color gdGradientWellnessTo = Color(0xFFF43F5E); // wellness gradient end
const Color gdGradientFinanceFrom = Color(0xFF10B981); // finance gradient start
const Color gdGradientFinanceTo = Color(0xFF059669); // finance gradient end
const Color gdGradientCreativeFrom = Color(0xFF8B5CF6); // creative gradient start
const Color gdGradientCreativeTo = Color(0xFFD946EF); // creative gradient end
const Color gdPetMintFrom = Color(0xFF22D3EE); // pet aqua gradient start
const Color gdPetMintTo = Color(0xFF2DD4BF); // pet mint gradient end
const Color gdPetAccent = Color(0xFFEAF2FF); // high-contrast soft text on dark blue
const Color gdOnDark = Color(0xFFFFFFFF); // readable foreground on dark surfaces
const Color gdOnDarkMuted = Color(0xFFF4F7FF); // readable secondary text on soft blue surfaces
const Color gdCardLight = Color(0xFFF8FAFC); // crisp light card background
const Color gdStarGold = Color(0xFFE9A63A); // energetic star rating gold color
const double gdTouchTarget = 52;
